#
# @COPYRIGHT@
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import(['env'])

doxyfile = env.Doxyfile(
    INPUT               = '..',
    RECURSIVE           = True,
    PROJECT_NAME        = "Dimbo Libraries",
    PROJECT_NUMBER      = '0.1.0',
    PROJECT_BRIEF       = 'Libraries that are part of Dimbo package',
    OUTPUT_DIRECTORY    = '.',
    STRIP_FROM_PATH     = '../../../..',
    STRIP_FROM_INC_PATH = '../..',
    EXAMPLE_PATH        = '../examples',
    FILTER_PATTERNS     = { '*.cpp' : env.File('#bin/doxycppfilter'),
                          '*.hpp' : env.File('#bin/doxycppfilter') }
)

doc = env.Doxygen(doxyfile)

env.Clean('..','.')
env.Ignore('..', '.')
env.Alias('api-doc', '.')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
