# @COPYRIGHT@
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

import re

# Default compilation flags for all subdirs
env.Append( CCFLAGS = '-g' )
if re.match(r'^(yes|true|1)$', env.get('DIMBO_ENABLE_GCOV','no'), re.I):
    env.Append( CCFLAGS = '-O0 -ftest-coverage -fprofile-arcs' )
    env.Append( LIBS = 'gcov' )
    env.Append( LINKFLAGS = '-coverage' )
else:
    env.Append( CCFLAGS = '-O2' )

env.Append( CCFLAGS = '-Werror -Wall -Wextra -pedantic' )
env.Append( CFLAGS = '-ansi -std=c1x' )
env.Append( CXXFLAGS = '-ansi -std=c++0x' )


subdirs = [ 'lib', 'app' ]
scripts = [ '%s/SConscript' % s for s in subdirs ]
SConscript( scripts, exports = ['env'] )

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
