# @COPYRIGHT@
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

from SCons.Util import CLVar

objects = env.SharedObject([
      'exception.cpp'
    , 'cl_error.cpp'
    , 'cl_error_no.cpp'
    , 'platform.cpp'
    , 'platforms.cpp'
    , 'platform_info.cpp'
    , 'platform_query.cpp'
    , 'device.cpp'
    , 'devices.cpp'
    , 'device_info.cpp'
    , 'device_query.cpp'
    , 'platform_layer.cpp'
    , 'platform_layer_info.cpp'
    , 'program.cpp'
    #, 'program_source.cpp'
    , 'context.cpp'
    , 'context_properties.cpp'
])

libs =  CLVar('dimbo_protobuf_cl boost_regex boost_serialization OpenCL')

# rlib - "real" library
rlib = env.SharedLibrary('../../dimbo_cl', objects + ['real.cpp'], LIBS = libs)
env.Install('${libdir}', rlib)

# tlib - library for testing (OpenCL functions replaced with mocks)
tlib = env.SharedLibrary('../../dimbo_cl_test', objects + ['mock.cpp'], LIBS = libs)
env.Ignore('../..', tlib)


# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
