# @COPYRIGHT@
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

libdimbo_cl = env.SharedLibrary(
  target = 'libdimbo_cl', 
  source = [
    'exception.cpp'
  , 'cl_error.cpp'
  , 'cl_error_no.cpp'
  , 'platform.cpp'
  , 'platforms.cpp'
  , 'platform_info.cpp'
  , 'platform_query.cpp'
  , 'device.cpp'
  , 'devices.cpp'
  , 'device_info.cpp'
  , 'device_query.cpp'
  , 'platform_layer.cpp'
  , 'platform_layer_info.cpp'
  , 'program.cpp'
  #, 'program_source.cpp'
  , 'context.cpp'
  , 'context_properties.cpp'
  ]
)

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
