/*
 * @COPYRIGHT@
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE
 */

/** // doc: dimbo/swig/dimbo/cl/cl_errors.swg {{{
 * \file dimbo/swig/dimbo/cl/cl_errors.swg
 * \todo Write documentation
 */ // }}}

%include <dimbo/cl/cl_errors/common.swg>
%include <dimbo/cl/cl_errors/cl_build_program_failure.swg>
%include <dimbo/cl/cl_errors/cl_compiler_not_available.swg>
%include <dimbo/cl/cl_errors/cl_device_not_available.swg>
%include <dimbo/cl/cl_errors/cl_device_not_found.swg>
%include <dimbo/cl/cl_errors/cl_image_format_mismatch.swg>
%include <dimbo/cl/cl_errors/cl_image_format_not_supported.swg>
%include <dimbo/cl/cl_errors/cl_invalid_arg_index.swg>
%include <dimbo/cl/cl_errors/cl_invalid_arg_size.swg>
%include <dimbo/cl/cl_errors/cl_invalid_arg_value.swg>
%include <dimbo/cl/cl_errors/cl_invalid_binary.swg>
%include <dimbo/cl/cl_errors/cl_invalid_buffer_size.swg>
%include <dimbo/cl/cl_errors/cl_invalid_build_options.swg>
%include <dimbo/cl/cl_errors/cl_invalid_command_queue.swg>
%include <dimbo/cl/cl_errors/cl_invalid_context.swg>
%include <dimbo/cl/cl_errors/cl_invalid_device.swg>
%include <dimbo/cl/cl_errors/cl_invalid_device_type.swg>
%include <dimbo/cl/cl_errors/cl_invalid_event.swg>
%include <dimbo/cl/cl_errors/cl_invalid_event_wait_list.swg>
%include <dimbo/cl/cl_errors/cl_invalid_global_offset.swg>
%include <dimbo/cl/cl_errors/cl_invalid_global_work_size.swg>
%include <dimbo/cl/cl_errors/cl_invalid_gl_object.swg>
%include <dimbo/cl/cl_errors/cl_invalid_host_ptr.swg>
%include <dimbo/cl/cl_errors/cl_invalid_image_format_descriptor.swg>
%include <dimbo/cl/cl_errors/cl_invalid_image_size.swg>
%include <dimbo/cl/cl_errors/cl_invalid_kernel_args.swg>
%include <dimbo/cl/cl_errors/cl_invalid_kernel_definition.swg>
%include <dimbo/cl/cl_errors/cl_invalid_kernel_name.swg>
%include <dimbo/cl/cl_errors/cl_invalid_kernel.swg>
%include <dimbo/cl/cl_errors/cl_invalid_mem_object.swg>
%include <dimbo/cl/cl_errors/cl_invalid_mip_level.swg>
%include <dimbo/cl/cl_errors/cl_invalid_operation.swg>
%include <dimbo/cl/cl_errors/cl_invalid_platform.swg>
%include <dimbo/cl/cl_errors/cl_invalid_program_executable.swg>
%include <dimbo/cl/cl_errors/cl_invalid_program.swg>
%include <dimbo/cl/cl_errors/cl_invalid_queue_properties.swg>
%include <dimbo/cl/cl_errors/cl_invalid_sampler.swg>
%include <dimbo/cl/cl_errors/cl_invalid_value.swg>
%include <dimbo/cl/cl_errors/cl_invalid_work_dimension.swg>
%include <dimbo/cl/cl_errors/cl_invalid_work_group_size.swg>
%include <dimbo/cl/cl_errors/cl_invalid_work_item_size.swg>
%include <dimbo/cl/cl_errors/cl_map_failure.swg>
%include <dimbo/cl/cl_errors/cl_mem_copy_overlap.swg>
%include <dimbo/cl/cl_errors/cl_mem_object_allocation_failure.swg>
%include <dimbo/cl/cl_errors/cl_out_of_host_memory.swg>
%include <dimbo/cl/cl_errors/cl_out_of_resources.swg>
%include <dimbo/cl/cl_errors/cl_profiling_info_not_available.swg>
%include <dimbo/cl/cl_errors/other_cl_error.swg>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
